# Site settings
name: Anas El Yousfi
title: Anas El Yousfi | Student
description: Anas El Yousfi
url: https://anaselyousfi.me
baseurl: ""
email: anaselyousfi@gmail.com
# cover: https://brittanychiang.com/img/og.png
# logo: https://brittanychiang.com/img/emojis/technologist.png
social:
  - title: email
    url: mailto:anaselyousfi@gmail.com
  - title: twitter
    url: https://twitter.com/TheYousfi
  - title: instagram
    url: https://instagram.com/anastheyousfi
  - title: github
    url: https://github.com/anaselyousfi
  - title: linkedin
    url: https://www.linkedin.com/in/anaselyousfi

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
